name: Build Application

on:
  push:
    branches: [ "main", "master" ] # Trigger on push to main or master branch
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Run build script
      run: python build.py

    - name: Upload Windows Installer
      uses: actions/upload-artifact@v4
      with:
        name: zenscript-windows-installer
        path: installers/*.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        brew install create-dmg

    - name: Run build script
      run: python build.py

    - name: Upload macOS DMG
      uses: actions/upload-artifact@v4
      with:
        name: zenscript-macos-dmg
        path: installers/*.dmg

  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
    - name: Prepare Arch Linux environment
      run: |
        pacman -Syu --noconfirm
        pacman -S --